changes done

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,4 +1,203 @@
+# docker-compose.yml
+
+version: "3"
+
 services:
+  db:
+    image: mariadb:10.6
+    networks:
+      - frappe_network
+    healthcheck:
+      test: mysqladmin ping -h localhost --password=admin
+      interval: 1s
+      retries: 20
+    command:
+      - --character-set-server=utf8mb4
+      - --collation-server=utf8mb4_unicode_ci
+      - --skip-character-set-client-handshake
+      - --skip-innodb-read-only-compressed
+    environment:
+      MYSQL_ROOT_PASSWORD: admin
+      MARIADB_ROOT_PASSWORD: admin
+    volumes:
+      - db-data:/var/lib/mysql
+
+  redis-queue:
+    image: redis:6.2-alpine
+    networks:
+      - frappe_network
+    volumes:
+      - redis-queue-data:/data
+
+  redis-cache:
+    image: redis:6.2-alpine
+    networks:
+      - frappe_network
+
+  backend:
+    image: frappe/erpnext:v15.69.2
+    networks:
+      - frappe_network
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+    environment:
+      DB_HOST: db
+      DB_PORT: "3306"
+      MYSQL_ROOT_PASSWORD: admin
+      MARIADB_ROOT_PASSWORD: admin
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.backend.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.preciseerp.com`)"
+      - "traefik.http.routers.backend.entrypoints=websecure"
+      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
+      - "traefik.http.services.backend.loadbalancer.server.port=8000"
+
+  frontend:
+    image: frappe/erpnext:v15.69.2
+    depends_on:
+      - websocket
+    networks:
+      - frappe_network
+    command: nginx-entrypoint.sh
+    environment:
+      BACKEND: backend:8000
+      FRAPPE_SITE_NAME_HEADER: frontend
+      SOCKETIO: websocket:9000
+      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
+      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
+      UPSTREAM_REAL_IP_RECURSIVE: "off"
+      PROXY_READ_TIMEOUT: 120
+      CLIENT_MAX_BODY_SIZE: 50m
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  websocket:
+    image: frappe/erpnext:v15.69.2
+    networks:
+      - frappe_network
+    command:
+      - node
+      - /home/frappe/frappe-bench/apps/frappe/socketio.js
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  scheduler:
+    image: frappe/erpnext:v15.69.2
+    networks:
+      - frappe_network
+    command:
+      - bench
+      - schedule
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  queue-long:
+    image: frappe/erpnext:v15.69.2
+    networks:
+      - frappe_network
+    command:
+      - bench
+      - worker
+      - --queue
+      - long,default,short
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  queue-short:
+    image: frappe/erpnext:v15.69.2
+    networks:
+      - frappe_network
+    command:
+      - bench
+      - worker
+      - --queue
+      - short,default
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  configurator:
+    image: frappe/erpnext:v15.69.2
+    networks:
+      - frappe_network
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - >
+        ls -1 apps > sites/apps.txt;
+        bench set-config -g db_host $$DB_HOST;
+        bench set-config -gp db_port $$DB_PORT;
+        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
+        bench set-config -gp socketio_port $$SOCKETIO_PORT;
+    environment:
+      DB_HOST: db
+      DB_PORT: "3306"
+      REDIS_CACHE: redis-cache:6379
+      REDIS_QUEUE: redis-queue:6379
+      SOCKETIO_PORT: "9000"
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  create-site:
+    image: frappe/erpnext:v15.69.2
+    networks:
+      - frappe_network
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - >
+        wait-for-it -t 120 db:3306;
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
+        bench new-site --mariadb-user-host-login-scope='%' --admin-password=admin --db-root-username=root --db-root-password=admin --install-app erpnext --set-default frontend;
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  django:
+    build: ./django
+    volumes:
+      - ./django:/app
+      - sites:/home/frappe/frappe-bench/sites
+    depends_on:
+      - backend
+    environment:
+      - DJANGO_SUPERUSER_USERNAME=admin
+      - DJANGO_SUPERUSER_PASSWORD=admin
+      - DJANGO_SUPERUSER_EMAIL=taher.badnawarwala@gmail.com
+    command: >
+      sh -c "python manage.py migrate && python manage.py createsu && python manage.py runserver 0.0.0.0:8000"
+    labels:
+      - "traefik.enable=true"
+      - "traefik.http.routers.django.rule=Host(`provision.preciseerp.com`)"
+      - "traefik.http.routers.django.entrypoints=websecure"
+      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
+      - "traefik.http.services.django.loadbalancer.server.port=8000"
+    networks: [frappe_network]
+
   traefik:
     image: traefik:v2.11
     command:
@@ -6,103 +205,21 @@ services:
       - --entrypoints.web.address=:80
       - --entrypoints.websecure.address=:443
       - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
-      - --certificatesresolvers.letsencrypt.acme.email=taher@saifytech.com
+      - --certificatesresolvers.letsencrypt.acme.email=taher.badnawarwala@gmail.com
       - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
     ports: ["80:80","443:443"]
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./traefik/traefik.yml:/traefik.yml
       - ./traefik/acme.json:/letsencrypt/acme.json
-    networks: [erpnet]
-
-  mariadb:
-    image: mariadb:10.6
-    env_file: [./envs/mariadb.env]
-    volumes: [mariadb-data:/var/lib/mysql]
-    networks: [erpnet]
-
-  redis-cache:
-    image: redis:alpine
-    networks: [erpnet]
-
-  redis-queue:
-    image: redis:alpine
-    networks: [erpnet]
-
-  redis-socketio:
-    image: redis:alpine
-    networks: [erpnet]
-
-  backend:
-    build:
-      context: ./erpnext
-      dockerfile: ./images/bench/Dockerfile
-      target: backend
-    depends_on: [mariadb]
-    env_file: [./envs/common.env, ./envs/sites.env]
-    volumes: [sites-vol:/home/frappe/frappe-bench/sites]
-    labels:
-      - "traefik.enable=true"
-      - "traefik.http.routers.erp.rule=HostRegexp(`{client:[a-z0-9-]+}.preciseerp.com`)"
-      - "traefik.http.routers.erp.entrypoints=websecure"
-      - "traefik.http.routers.erp.tls.certresolver=letsencrypt"
-      - "traefik.http.services.erp.loadbalancer.server.port=8000"
-    networks: [erpnet]
-
-  scheduler:
-    build:
-      context: ./erpnext
-      dockerfile: ./images/bench/Dockerfile
-      target: scheduler
-    depends_on: [backend]
-    env_file: [./envs/common.env, ./envs/sites.env]
-    volumes: [sites-vol:/home/frappe/frappe-bench/sites]
-    networks: [erpnet]
-
-  worker:
-    build:
-      context: ./erpnext
-      dockerfile: ./images/bench/Dockerfile
-      target: worker
-    depends_on: [backend]
-    env_file: [./envs/common.env, ./envs/sites.env]
-    volumes: [sites-vol:/home/frappe/frappe-bench/sites]
-    networks: [erpnet]
-
-  frontend:
-    build:
-      context: ./erpnext
-      dockerfile: ./images/production/Containerfile
-    depends_on: [backend]
-    volumes: [sites-vol:/home/frappe/frappe-bench/sites]
-    networks: [erpnet]
-
-  django:
-    build: ./django
-    volumes:
-      - ./django:/app
-      - sites-vol:/home/frappe/frappe-bench/sites
-    depends_on: [backend]
-    environment:
-      - DJANGO_SUPERUSER_USERNAME=admin
-      - DJANGO_SUPERUSER_PASSWORD=admin
-      - DJANGO_SUPERUSER_EMAIL=admin@example.com
-    command: >
-      sh -c "python manage.py migrate &&
-             python manage.py createsu &&
-             python manage.py runserver 0.0.0.0:8000"
-    labels:
-      - "traefik.enable=true"
-      - "traefik.http.routers.django.rule=Host(`provision.preciseerp.com`)"
-      - "traefik.http.routers.django.entrypoints=websecure"
-      - "traefik.http.routers.django.tls.certresolver=letsencrypt"
-      - "traefik.http.services.django.loadbalancer.server.port=8000"
-    networks: [erpnet]
+    networks: [frappe_network]
 
 volumes:
-  mariadb-data:
-  sites-vol:
+  db-data:
+  redis-queue-data:
+  sites:
+  logs:
 
 networks:
-  erpnet:
+  frappe_network:
     driver: bridge
